#!/usr/bin/env bash
set -euo pipefail

echo "1) Installing dependencies (pnpm install --recursive)..."
pnpm install --recursive

echo "2) Generating RPC code (buf generate) - if you have buf configured."
# If you are using buf, uncomment the next line. If not, make sure client & server stubs are generated by your preferred generator.
buf generate

echo "3) Starting backend and frontend concurrently..."
# Start backend and frontend in parallel
(cd backend && pnpm dev) &
BACKEND_PID=$!

(cd frontend && pnpm dev) &
FRONTEND_PID=$!

echo "Backend started with PID: $BACKEND_PID"
echo "Frontend started with PID: $FRONTEND_PID"
echo "Application will be available at: http://localhost:3000"

# Wait for both processes
wait $BACKEND_PID $FRONTEND_PID
